### Site Settings ###
title               : Ilyan Aza-lun
description         : 
                      I turn coffee :coffee: into code,
                      use tabs over spaces
                      and never broke production.
baseurl             : "/ilyanazalun.github.io"                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : ilyanazalun/ilyanazalun     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/partials/**                           # For Documentation Only


### Author Info ###
author:
  name              : Iyang Agung Supriatna
  image             : https://i.imgur.com/uyDNQnn.jpg
  behance           : ilyanazalun
# dribbble          : ilyanazalun
  email             : username@domain.com
  facebook          : ilyanazalun
  github            : ilyanazalun
# gitlab            : ilyanazalun
# instagram         : ilyanazalun
# kaggle            : ilyanazalun
  linkedin          : ilyanazalun
  medium            : ilyanazalun
# soundcloud        : ilyanazalun
# spotify           : ilyanazalun
# stackoverflow     : your_user_id
# tumblr            : ilyanazalun.tumblr.com
# twitch            : ilyanazalun
  twitter           : ilyanazalun
# vimeo             : ilyanazalun
# youtube           : your_channel_name
# keybase           : ilyanazalun


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  elements:                                             # For Documentation Only
    output: true                                        # For Documentation Only


### Disqus ###
disqus:
  shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:                                              # For Documentation Only
      path: ""                                          # For Documentation Only
      type: "elements"                                  # For Documentation Only
    values:                                             # For Documentation Only
      layout: "element"                                 # For Documentation Only
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
